# Generated by Django 4.2.10 on 2024-02-13 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_account_id_account_id_alter_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='_balance',
        ),
    ]
